---
version: '2.1'

services:

  rpa-native-pdf-annotator-db:
    image: postgres
    environment:
      - POSTGRES_USER=emnpa
      - POSTGRES_PASSWORD=emnpa
      - POSTGRES_DB=emnpa
    ports:
      - 5433:5432

  service-auth-provider-api:
    image: hmctspublic.azurecr.io/rpe/service-auth-provider:latest
    environment:
      - jwtKey=wThK0f0/lh3FlxFcL4xUWDMI5C1J9KyQBgXV4wseh1e5J1uYJIjvTvArHxQDrYoHJ23xFxjHkOnvNbR5dXRoxA==
      - microserviceKeys_em_gw=AAAAAAAAAAAAAAAA
      - microserviceKeys_em_npa_app=AAAAAAAAAAAAAAAA
#      logging env vars
      - JSON_CONSOLE_PRETTY_PRINT=false
      - REFORM_SERVICE_TYPE=java
      - REFORM_SERVICE_NAME=service-auth-provider-api
      - REFORM_TEAM=rpe
      - REFORM_ENVIRONMENT=docker
#      healthcheck env vars
      - PACKAGES_ENVIRONMENT=docker
      - PACKAGES_PROJECT=rpe
      - PACKAGES_NAME=service-auth-provider-api
      - PACKAGES_VERSION=unkown
      - TESTING_SUPPORT_ENABLED=true
    ports:
      - 4502:8489

  annotation-api:
    image: hmctspublic.azurecr.io/em/anno:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://annotation-api-db:5432/anno
      - SPRING_DATASOURCE_USERNAME=anno
      - SPRING_DATASOURCE_PASSWORD=anno
      - S2S_BASE_URI=http://service-auth-provider-api:8489
      - IDAM_API_BASE_URI=http://idam-api:8080
      - ENABLE_LIQUIBASE=true
    links:
    - annotation-api-db
    depends_on:
    - annotation-api-db
    ports:
    - 4623:8080

  annotation-api-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=anno
      - POSTGRES_USER=anno
      - POSTGRES_PASSWORD=anno

  idam-api:
    image: hmctspublic.azurecr.io/idam/api:stable
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      - JAVA_TOOL_OPTIONS=-Xms128m -Xmx512m -XX:MaxPermSize=512m
      - SPRING_PROFILES_ACTIVE=local
      - CACHING_ENABLED=false
      - SPRING_DATA_ELASTICSEARCH_PROPERTIES_PATH_HOME=/tmp/es
      - TESTING_SUPPORT_ENABLED=true
      - IDAMHEALTHCHECK_AM_ENABLED=false
      - IDAMHEALTHCHECK_IDM_ENABLED=false
      - STRATEGIC_ADMIN_URL=http://idam-web-admin:8082
      - STRATEGIC_WEBPUBLIC_URL=http://idam-web-public:9002
      - SPRING_DATASOURCE_URL=jdbc:postgresql://shared-db:5432/openidm?currentSchema=fridam
      - SPRING_DATASOURCE_USERNAME=openidm
      - SPRING_DATASOURCE_PASSWORD=openidm
      - SECURITY_OAUTH2_CLIENT_CLIENTSECRET=password
      - SECURITY_OAUTH2_CLIENT_PRE_ESTABLISHED_REDIRECT_URI=http://idam-web-public:9002/login
      - SECURITY_OAUTH2_CLIENT_REGISTERED_REDIRECT_URI=http://idam-web-public:9002/login
      - IDAM_SPI_FORGEROCK_AM_ROOT=http://fr-am:8080/openam
      - IDAM_SPI_FORGEROCK_AM_TOPLEVELHOST=fr-am
      - IDAM_SPI_FORGEROCK_AM_USERNAME=amadmin
      - IDAM_SPI_FORGEROCK_AM_PASSWORD=Pa55word11
      - IDAM_SPI_FORGEROCK_AM_JWKSURIFOROAUTH2CLIENTS=http://fr-am:8080/openam/oauth2/hmcts/connect/jwk_uri
      - IDAM_SPI_FORGEROCK_IDM_ROOT=http://fr-idm:18080/openidm
      - IDAM_SPI_FORGEROCK_IDM_USERNAME=openidm-admin
      - IDAM_SPI_FORGEROCK_IDM_PASSWORD=openidm-admin
      - IDAM_SPI_FORGEROCK_IDM_PIN_DEFAULTPASSWORD=BlaBlaBlackSh33p
      - IDAM_API_OAUTH2_CLIENT_CLIENT_SECRETS_WEBSHOW=AAAAAAAAAAAAAAAA
      - IDAM_WEBSHOW_WHITELIST=http://localhost:8080/oauth2redirect
      - REFORM_SERVICE_NAME=idam-api
      - REFORM_TEAM=idam
      - REFORM_ENVIRONMENT=local
    ports:
      - 5000:5000

  idam-web-public:
    image: hmctspublic.azurecr.io/idam/web-public:stable
    environment:
      - JAVA_OPTS=-Xms128m -Xms512m
      - STRATEGIC_SERVICE_URL=http://idam-api:5000
    ports:
      - 9002:8080
    depends_on:
      - idam-api

  idam-web-admin:
    image: hmctspublic.azurecr.io/idam/web-admin:stable
    environment:
      - JAVA_OPTS=-Xms128m -Xms512m
      - STRATEGIC_SERVICE_URL=http://idam-api:5000
      - STRATEGIC_PUBLIC_URL=http://idam-web-public:9002
    ports:
      - 8082:8080
    depends_on:
      - idam-api

  smtp-server:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

  dm-store:
    image: hmctspublic.azurecr.io/dm/store:latest
    environment:
      - SERVER_PORT=8080
      - IDAM_SUPERUSER_EMAIL
      - IDAM_SECRET_KEY=AAAAAAAAAAAAAAAA
      - GOV_NOTIFY_API_KEY
      - ENABLE_DB_MIGRATE=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dm-store-db:5432/evidence
      - SPRING_DATASOURCE_USERNAME=evidence
      - SPRING_DATASOURCE_PASSWORD=evidence
      - SPRING_PROFILES_ACTIVE=dev
      - ENABLE_AZURE_STORAGE_CONTAINER=true
      - ENABLE_POSTGRES_BLOB_STORAGE=false
      - STORAGEACCOUNT_PRIMARY_CONNECTION_STRING=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azure-storage-emulator-azurite:10000/devstoreaccount1
      - STORAGE_CONTAINER_DOCUMENT_CONTAINER_NAME=hmctstestcontainer
      - BLOBSTORE_MIGRATE_CCD_PUBLIC_KEY_REQUIRED=false
      - BLOBSTORE_MIGRATE_CCD_PUBLIC_KEY="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDiQ//gc/G53d9dLCtf123fIYo49gUySuJuxOcw2GtieWTMSy+O7RNtsAIjVf3mCOdDNuN69tZNPEWMdaW8n11s9MwYFahtxDecyn0KIP9MvPsfSMSbxhp/f7kfbdB/H/S5eYea66JTyeJS6uNd76RdHttx0mLO30ZkRcXB25c2SIXhRYsdoeKS5GXHDdNejkQM0S/Ev94x2UunApmYHjWN1XcDhsEsAeF4WHnvYh2XiMn9vHY44AqvbWLlAmCgzaXpz8Xhl0fO7jDKSeReDyuM3UTMaiFFaxuvliGol7aIXq/aVe/miiD2SLxHZ6RxAPW80bhXrzJMTLTCqhCEhzfv someone@somewhere.sometime"
      - IDAM_TESTING_SUPPORT_ENABLED=true
      - LOGGING_LEVEL_UK_GOV_HMCTS_IDAM=DEBUG
      - IDAM_S2S_BASE_URI=http://service-auth-provider-api:8489
      - S2S_NAMES_WHITELIST=em_npa_app,sscs,divorce,ccd,em_gw,ccd_gw,em_stitching_api,em_ccd_orchestrator
      - http_proxy=
      - https_proxy=
      - no_proxy=
      #      logging env vars
      - JSON_CONSOLE_PRETTY_PRINT=false
      - REFORM_SERVICE_TYPE=java
      - REFORM_SERVICE_NAME=dm-store
      - REFORM_TEAM=evidence
      - REFORM_ENVIRONMENT=docker
      #      healthcheck env vars
      - PACKAGES_ENVIRONMENT=docker
      - PACKAGES_PROJECT=evidence
      - PACKAGES_NAME=dm-store
      - PACKAGES_VERSION=unkown
      #      debug mode
      - JAVA_OPTS=-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005
    links:
      - dm-store-db
      - service-auth-provider-api
      - make-container-call
    depends_on:
      - dm-store-db
      - service-auth-provider-api
      - make-container-call
    ports:
      - 4603:8080

  dm-store-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=evidence
      - POSTGRES_USER=evidence
      - POSTGRES_PASSWORD=evidence
    ports:
      - 5435:5432

  fr-am:
    image: hmctsprivate.azurecr.io/idam/idam-fr-am:latest
    environment:
      - JAVA_TOOL_OPTIONS=-Xms128m -Xmx512m -XX:MaxPermSize=512m
    hostname: localam
    ports:
      - 9080:8080
      - 1389:1389
    depends_on:
      - shared-db

  fr-idm:
    image: hmctsprivate.azurecr.io/idam/idam-fr-idm:latest
    environment:
      - JAVA_TOOL_OPTIONS=-Xms128m -Xmx512m -XX:MaxPermSize=512m
    hostname: localidm
    ports:
      - 18080:18080
      - 9010:9010
    depends_on:
      - fr-am
      - shared-db

  shared-db:
    image: hmctsprivate.azurecr.io/idam/shared-db:latest
    ports:
      - 5430:5432

  azure-storage-emulator-azurite:
    image: arafato/azurite
    ports:
      - 10000:10000
    environment:
      executable: "blob"
    volumes:
      - ccd-docker-azure-blob-data:/opt/azurite/folder

  make-container-call:
    image: byrnedo/alpine-curl
    command: -XPUT --verbose http://azure-storage-emulator-azurite:10000/devstoreaccount1/hmctstestcontainer?restype=container
    links:
      - azure-storage-emulator-azurite
    depends_on:
      - azure-storage-emulator-azurite

volumes:
  ccd-docker-azure-blob-data:
